# Generated by Django 2.1.7 on 2019-06-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20190630_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
