# Generated by Django 2.1.7 on 2019-06-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20190701_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='deadline',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
