# Generated by Django 2.1.7 on 2019-07-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20190701_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='priority',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
