# Generated by Django 2.1.7 on 2019-07-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
