# Generated by Django 2.1.7 on 2019-07-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='files',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
