# Generated by Django 2.1.7 on 2019-07-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20190702_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='comments/files'),
        ),
    ]
